---
# Install application from git repository and telegraf
- hosts: application_nodes
  become: yes
  vars:
    jar_location: /opt/temp/target/rental-app-0.0.1-SNAPSHOT.jar
    app_location: /opt/car-rental-app/car-rental-app.jar
    app_user: rentalapp
    metrics_storage_ip: 172.31.23.78
  tasks:
    - include_tasks: tasks/application.yml

# Install load balancer and ssl
- hosts: proxy_nodes
  become: yes
  vars:
    email: test@gmail.com
    domain: aapkaa.tk
  tasks:
  - include_tasks: tasks/proxy.yml

# Install influxdb and grafana
- hosts: metrics_storage
  become: yes
  tasks:
  - include_tasks: tasks/metrics.yml

# Install mongodb
- hosts: database_nodes
  become: yes
  tasks:
  - include_tasks: tasks/mongo.yml