---
- hosts: app_nodes
  become: yes
  tasks:
    - yum:
        name: httpd
        state: present
    - service:
        name: httpd
        state: started
- hosts: proxy_nodes
  tasks:
    - yum:
       name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
       state: present